import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Designs.module.css'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import Contact from '@/components/Contact'

export default function Designs() {
    return (
        <>
            <Head>
                <title>Mariessa Pinto Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.introSection}>
                    <Navbar />
                    <div className={styles.topContent}>
                        <div>
                            <h1>Under Construction</h1>
                            <h1>Design Projects</h1>
                        </div>
                    </div>
                </div>
                <div className={styles.grid}>
                </div>
                <div id="contactSection" className={styles.contactSection}>
                    <Contact />
                </div>
            </main>
        </>
    )
}