import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import ProjectCard from '@/components/ProjectCard'
import Contact from '@/components/Contact'


export default function Home({ props }) {
  return (
    <>
      <Head>
        <title>Mariessa Pinto Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        </style>
      </Head>
      <main className={styles.main}>
        <div className={styles.introSection}>
          <Navbar />
          <div className={styles.topContent}>
            <div>
              <h1>Hi, I'm Mariessa.</h1>
              <p>a passionate web developer and project manager who loves learning new things.</p>
              <p>works to find new challenges, adopt new perspectives, and realize new solutions to optimize project outcomes.</p>
              <button>View Projects</button>
            </div>
            <div>
              <Image
                src={""}
                alt=''
                width={300}
                height={300}
              />
            </div>
          </div>
        </div>
        <div className={styles.projects}>
          <h2>Web Development</h2>
          <ProjectCard
            title="Innersight"
            subtitle="Dates of Project"
            description='Lorem ipsum dolor sit amet consectetur. Scelerisque sit imperdiet elementum sed in sit orci. Scelerisque sit imperdiet elementum sed in sit orci.'
            projectURL='/caseStudy'
            imageSrc=''
          />
          <ProjectCard
            title="Borderless"
            subtitle="Dates of Project"
            description='Lorem ipsum dolor sit amet consectetur. Scelerisque sit imperdiet elementum sed in sit orci. Scelerisque sit imperdiet elementum sed in sit orci.'
            projectURL='/projectOne'
            imageSrc=''
          />
          <ProjectCard
            title="i18n Showcase - BCIT English-French"
            subtitle="Dates of Project"
            description='Lorem ipsum dolor sit amet consectetur. Scelerisque sit imperdiet elementum sed in sit orci. Scelerisque sit imperdiet elementum sed in sit orci.'
            projectURL='/projectTwo'
            imageSrc=''
          />
          <ProjectCard
            title="Pagepal"
            subtitle="Dates of Project"
            description='Lorem ipsum dolor sit amet consectetur. Scelerisque sit imperdiet elementum sed in sit orci. Scelerisque sit imperdiet elementum sed in sit orci.'
            projectURL='/projectThree'
            imageSrc=''
          />
        </div>
        <div className={styles.contactSection}>
          <Contact />
        </div>
      </main>
    </>
  )
}
